//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportManager.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ReportManager.Resources.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max length of category name is 100 signs!.
        /// </summary>
        internal static string CategoryNameMaxLengthErrorMessage {
            get {
                return ResourceManager.GetString("CategoryNameMaxLengthErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min length of category name is 10 signs!.
        /// </summary>
        internal static string CategoryNameMinLengthErrorMessage {
            get {
                return ResourceManager.GetString("CategoryNameMinLengthErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category name is required!.
        /// </summary>
        internal static string CategoryNameRequiredErrorMessage {
            get {
                return ResourceManager.GetString("CategoryNameRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max length of person name is 100 signs!.
        /// </summary>
        internal static string PersonNameMaxLengthErrorMessage {
            get {
                return ResourceManager.GetString("PersonNameMaxLengthErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min length of person name is 10 signs!.
        /// </summary>
        internal static string PersonNameMinLengthErrorMessage {
            get {
                return ResourceManager.GetString("PersonNameMinLengthErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person name is required!.
        /// </summary>
        internal static string PersonNameRequiredErrorMessage {
            get {
                return ResourceManager.GetString("PersonNameRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max length of project name is 100 signs!.
        /// </summary>
        internal static string ProjectNameMaxLengthErrorMessage {
            get {
                return ResourceManager.GetString("ProjectNameMaxLengthErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min length of project name is 10 signs!.
        /// </summary>
        internal static string ProjectNameMinLengthErrorMessage {
            get {
                return ResourceManager.GetString("ProjectNameMinLengthErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project name is required!.
        /// </summary>
        internal static string ProjectNameRequiredErrorMessage {
            get {
                return ResourceManager.GetString("ProjectNameRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to select the category!.
        /// </summary>
        internal static string ReportCatIdRequiredErrorMessage {
            get {
                return ResourceManager.GetString("ReportCatIdRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum length of description is 1000 signs!.
        /// </summary>
        internal static string ReportDescMaxLengthErrorMessage {
            get {
                return ResourceManager.GetString("ReportDescMaxLengthErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimal length of description is 50 signs!.
        /// </summary>
        internal static string ReportDescMinLengthErrorMessage {
            get {
                return ResourceManager.GetString("ReportDescMinLengthErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem description is required!.
        /// </summary>
        internal static string ReportDescRequiredErrorMessage {
            get {
                return ResourceManager.GetString("ReportDescRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to select related project!.
        /// </summary>
        internal static string ReportProjIdRequiredErrorMessage {
            get {
                return ResourceManager.GetString("ReportProjIdRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum length of title is 50 signs!.
        /// </summary>
        internal static string ReportTitleMaxLengthErrorMessage {
            get {
                return ResourceManager.GetString("ReportTitleMaxLengthErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimal length of title is 5 signs!.
        /// </summary>
        internal static string ReportTitleMinLengthErrorMessage {
            get {
                return ResourceManager.GetString("ReportTitleMinLengthErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report title is required!.
        /// </summary>
        internal static string ReportTitleRequiredErrorMessage {
            get {
                return ResourceManager.GetString("ReportTitleRequiredErrorMessage", resourceCulture);
            }
        }
    }
}
